import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Component/navbar";
import Layout from "./Component/Layout";
import { ShoppingCartContextProvider } from "./context/ShoppingCartContext";


export const metadata: Metadata = {
  title: "Pari store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative min-h-screen bg-gradient-to-b from-slate-950 via-indigo-950 to-black text-slate-100">
        <div className="pointer-events-none absolute inset-0 [background-image:radial-gradient(rgba(255,255,255,0.06)_1px,transparent_1px)] [background-size:24px_24px] [mask-image:linear-gradient(to_bottom,black,transparent_85%)]" />
        <ShoppingCartContextProvider>
          <Layout>
            {children}
          </Layout>
        </ShoppingCartContextProvider>
      </body>
    </html>
  );
}
